#!/bin/sh

CF_FG_Y='\e[36;1m'
#CF_FG_R='\e[1m\e[30;42;5m'
CF_FG_R='\e[30;42m'
CF_UNDERLINE='\e[36;4m'
CF_RESET='\e[0m'

PACMAN=`which powerpill 2>/dev/null` || PACMAN=`which pacman-color 2>/dev/null` || PACMAN=`which pacman 2>/dev/null` || exit


checkArgv()
{
	(( 1 != $# )) && echo 'Avalid optios:--list --install --uninstall' && return 1
	if [[ '--list' == $1 ]]; then
		for i in ${ARR_PACMAN[@]}; do
			echo $i
		done

		for i in ${ARR_YAOURT[@]}; do
			echo $i
		done
	fi
}

hasInstalled()
{
	pacman -Q $1 &>/dev/null
}

optionType()
{
	[[ '--list' == $1 ]] && return 0
	[[ '--install' == $1 ]] && return 1
	[[ '--uninstall' == $1 ]] && return 2
	return 99
}

install()
{
	hasInstalled $1 && [[ 0 == $? ]] && echo -e "\e[32;6m$1\e[0m has been installed,contine..." && return

	echo -e "Would you like to ${CF_FG_Y}I${CF_RESET}nstall ${CF_FG_R}$1${CF_RESET}?(${CF_UNDERLINE}y/n${CF_RESET})"
	read yn
	[[ 'n' == $yn || 'no' == $yn ]] && return

	EXE=$PACMAN
	(( 2 == $# )) && EXE=$2
	
	F_SH="./$1.sh" 
	if [[ -f $F_SH ]]; then
		sh $F_SH --install
	else
		$EXE -S $1 #--noconfirm
	fi

	if (( 0 == $? )); then
		echo -e "\e[1m\e[32;4mSuccess to $EXE -S $1.\e[0m"
	else
		echo -e "\e[31;7mFail to $EXE -S $1!\e[0m"
	fi
}

uninstall()
{
	hasInstalled $1 || return 1

	echo -e "Would you like to ${CF_FG_Y}U${CF_RESET}ninstall ${CF_FG_R}$1${CF_RESET}?(${CF_UNDERLINE}y/n${CF_RESET})"
	read yn
	[[ 'n' == $yn || 'no' == $yn ]] && return

	EXE=$PACMAN
	#(( 2 == $# )) && EXE=$2
	
	F_SH="./$1.sh" 
	if [[ -f $F_SH ]]; then
		sh $F_SH --uninstall
	else
		$EXE -Rns $1
	fi

	if (( 0 == $? )); then
		echo -e "\e[1m\e[32;4mSuccess to $EXE -Rns $1.\e[0m"
	else
		echo -e "\e[31;7mFail to $EXE -Rns $1!\e[0m"
	fi
}
